### ISSUE TITLE
Error message when running v0.2.34

### ISSUE THREAD

**Issue by meganforbes** [gt-sse-center/RepoAuditor#118]
## Describe the bug
Starting off by saying I am NOT a software engineer or even someone with any real Python experience. So, this could very well be user error vs. a bug. You won't hurt my feelings by responding that. 

I ran RepoAuditor successfully two weeks ago, but after upgrading to v0.2.34 and running the test audit against python-helloworld, it no longer worked, returning the error message:

ERROR: module 'dbrownell_Common.ExecuteTasks' has no attribute 'TransformResultComplete'

## To Reproduce
1. Enter uv run repo_auditor --include GitHub --GitHub-url https://github.com/meganforbes/python-helloworld --GitHub-pat PAT
2. Message returned:

Processing 1 module...
  Processing 'GitHub' (1 of 1)...DONE! (-1, 0:00:00.005229)
DONE! (-1, 0:00:00.005799)
ERROR: module 'dbrownell_Common.ExecuteTasks' has no attribute 'TransformResultComplete'

Results: DONE! (-1, 0:00:00.007154)

## Expected behavior
I expected to receive an audit of the python-helloworld repository.

## Environment (please complete the following information):
 - OS: Windows 11, powershell terminal (also tried via Git Bash)
 - Python Version: 3.12.10
 - RepoAuditor Version: 0.2.34

**Comment by meganforbes** [comment]
Thanks! I am on the road this week but will re-try next week when I'm back at my desk.
